import React,{useEffect,useState}from'react'
import{createRoot}from'react-dom/client'
import{Briefcase,RefreshCw,Star,ExternalLink,FileText,Kanban,LayoutDashboard,Search,Download}from'lucide-react'
import{BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer}from'recharts'
import'./style.css'
const API='/api'
const api=async(p,o={})=>{const r=await fetch(API+p,{headers:{'Content-Type':'application/json'},...o});if(!r.ok)throw new Error(await r.text());return r.json()}
const statuses=['New','Saved','Applied','Interview','Offer','Rejected']
function App(){const[page,setPage]=useState('dashboard'),[jobs,setJobs]=useState([]),[dash,setDash]=useState(null),[sel,setSel]=useState(null),[filters,setFilters]=useState({status:'',q:'',remote_type:'',source:'',min_score:0});const load=()=>{api('/dashboard').then(setDash);api('/jobs?'+new URLSearchParams(filters)).then(setJobs)};useEffect(load,[JSON.stringify(filters)]);const open=async j=>{setSel(await api('/jobs/'+j.id));setPage('detail')};const run=async()=>{await api('/scrape',{method:'POST'});load()};return <div><header><div><h1>Job Watch Assistant</h1><p>Self-hosted job monitoring for Michael. Job boards are hostile markup wrapped in tracking pixels.</p></div><nav>{[['dashboard','Dashboard',LayoutDashboard],['jobs','Jobs',Briefcase],['kanban','Pipeline',Kanban]].map(([id,l,I])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><I/> {l}</button>)}<button onClick={run}><RefreshCw/> Scrape now</button></nav></header><main>{page==='dashboard'&&<Dashboard dash={dash} jobs={jobs} open={open}/>} {page==='jobs'&&<Jobs jobs={jobs} open={open} filters={filters} setFilters={setFilters}/>} {page==='kanban'&&<KanbanView jobs={jobs} open={open} reload={load}/>} {page==='detail'&&sel&&<Detail job={sel} setJob={setSel} reload={load}/>}</main></div>}
function Dashboard({dash,jobs,open}){let data=Object.entries(dash?.score_distribution||{}).map(([name,value])=>({name,value}));return <div className="grid"><section className="hero"><h2>Dashboard</h2><p>Criteria: Lowell MA 50-mile radius, remote nationwide, target $115k-$120k, ideal hybrid within 40 miles with $115k+ and bonus potential. Jobs below criteria are flagged, not hidden.</p><div className="metrics"><Metric l="New today" v={dash?.new_today||0}/><Metric l="Total tracked" v={dash?.total||0}/><Metric l="Applied / active" v={dash?.applied||0}/></div></section><section className="card"><h3>Match score distribution</h3><div className="chart"><ResponsiveContainer><BarChart data={data}><XAxis dataKey="name" stroke="#94a3b8"/><YAxis stroke="#94a3b8"/><Tooltip/><Bar dataKey="value" fill="#f97316" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div></section><section><h3>Top matches</h3><div className="jobs">{jobs.slice(0,8).map(j=><JobCard key={j.id} j={j} open={open}/>)}</div></section></div>}
function Metric({l,v}){return <div className="metric"><b>{v}</b><span>{l}</span></div>}
function Jobs({jobs,open,filters,setFilters}){return <div><div className="toolbar"><Search/><input placeholder="title, company, location" value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})}/><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><select value={filters.remote_type} onChange={e=>setFilters({...filters,remote_type:e.target.value})}><option value="">Any work mode</option>{['remote','hybrid','onsite','unknown'].map(s=><option key={s}>{s}</option>)}</select><select value={filters.source} onChange={e=>setFilters({...filters,source:e.target.value})}><option value="">All sources</option>{['Indeed','LinkedIn','Dice','ZipRecruiter','Manual'].map(s=><option key={s}>{s}</option>)}</select><input type="number" min="0" max="100" value={filters.min_score} onChange={e=>setFilters({...filters,min_score:e.target.value})}/></div><div className="jobs">{jobs.map(j=><JobCard key={j.id} j={j} open={open}/>)}</div></div>}
function JobCard({j,open}){return <button className={'job '+(j.ideal_match?'ideal':'')} onClick={()=>open(j)}><div className="jobtop"><span>{j.source}</span>{j.ideal_match&&<b className="gold"><Star/> Ideal</b>}</div><h3>{j.title}</h3><p>{j.company||'Unknown company'} · {j.location||'Unknown location'}</p><p>{j.salary||'Salary not listed'} · {j.remote_type}</p><div className="score"><span style={{width:j.match_score+'%'}}></span></div><b>{j.match_score}/100</b><small>{j.fit_summary}</small></button>}
function KanbanView({jobs,open,reload}){const move=async(j,s)=>{await api('/jobs/'+j.id+'/status',{method:'POST',body:JSON.stringify({status:s})});reload()};return <div className="kanban">{statuses.map(s=><section key={s}><h2>{s}</h2>{jobs.filter(j=>j.status===s).map(j=><div className="ticket" key={j.id} onClick={()=>open(j)}><b>{j.title}</b><p>{j.company}</p><select value={j.status} onClick={e=>e.stopPropagation()} onChange={e=>move(j,e.target.value)}>{statuses.map(x=><option key={x}>{x}</option>)}</select></div>)}</section>)}</div>}
function Detail({job,setJob,reload}){const[busy,setBusy]=useState('');const gen=async kind=>{setBusy(kind);await api('/jobs/'+job.id+'/generate',{method:'POST',body:JSON.stringify({kind})});setBusy('');setJob(await api('/jobs/'+job.id))};const status=async s=>{setJob(await api('/jobs/'+job.id+'/status',{method:'POST',body:JSON.stringify({status:s})}));reload()};return <div className="detail"><aside className="card"><button onClick={()=>setJob(null)}>Close</button><div className="jobtop"><span>{job.source}</span>{job.ideal_match&&<b className="gold"><Star/> Ideal match</b>}</div><h2>{job.title}</h2><p>{job.company} · {job.location}</p><p>{job.salary||'Salary not listed'} · {job.remote_type}</p><h1>{job.match_score}/100</h1><p>{job.fit_summary}</p><select value={job.status} onChange={e=>status(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select><a className="btn" href={job.url||'#'} target="_blank"><ExternalLink/> Apply / source URL</a><button onClick={()=>gen('cover_letter')} disabled={busy}><FileText/> Generate Cover Letter</button><button onClick={()=>gen('tailored_resume')} disabled={busy}><FileText/> Generate Tailored Resume</button></aside><section className="card"><h3>Match breakdown</h3><pre>{JSON.stringify(job.score_breakdown,null,2)}</pre><h3>Description</h3><p className="desc">{job.description||'No full description captured yet. Public boards frequently hide it behind JavaScript because they hate automation.'}</p><h3>Generated documents</h3>{job.generated_docs?.map(d=><div className="doc" key={d.id}><b>{d.title}</b><pre>{d.content}</pre><a href={API+'/docs/'+d.id+'/export/docx'}><Download/> DOCX</a><a href={API+'/docs/'+d.id+'/export/pdf'}><Download/> PDF</a></div>)}</section></div>}
createRoot(document.getElementById('root')).render(<App/>)
